book=('The Ultimate Guide to Python Programming','Tedlister Kent',2024,200_000)
title,author,publicationYear,price=book
print(f"The Title Of the book is:\n {title}")
print(f"\nThe Author of the book is:\n {author}")
print(f"\nThe Publication Year of the book is: {publicationYear}")
print(f"\nThe Price of the book is: {price}")
title=book.count('The Ultimate Guide to Python Programming')
print(f"\nTitle appears {title} time")
author=book.count('Tedlister Kent')
print(f"The author appears {author} time")
year=book.count(2024)
print(f"The publication year appears {year} time")
price=book.count(200_000)
print(f"The book price appears {price} time")
#retreiving the index
ib=book.index('The Ultimate Guide to Python Programming')
print(f"\nTitle index is: {ib}")
ia=book.index('Tedlister Kent')
print(f"Author index is: {ia}")
ipy=book.index(2024)
print(f"Index of publication year is: {ipy}")
ip=book.index(200_000)
print(f"Price index is: {ip}")
